### ISSUE TITLE
Change the color of the navabar to rgb(89, 16, 16)

### ISSUE THREAD

**Issue by Akshat2Jain** [Akshat2Jain/blogapp_reactjs#1]
# Change the colour of the navbar to rgb(89, 16, 16)

![Screenshot from 2022-07-06 16-32-31](https://user-images.githubusercontent.com/101265586/177553455-c31c9bf6-2550-46e8-b405-3eea70ad70ff.png)

## steps to follow
- Go to the src->index.css
- then go to the .navbar and change the background colour

## It should look something like this 
![Screenshot from 2022-07-06 18-21-08](https://user-images.githubusercontent.com/101265586/177554259-1fa32c5f-6c0c-41c4-bc11-fc97835f8f6f.png)

*I would love your contribution*

**Comment by themujahidkhan** [comment]
I want to contribute on this, can I? and also I would like to change the `navbar a` color to white so links will be visible on the background color, else pink color that background makes hard to find the nav links.

**Comment by Akshat2Jain** [comment]
> I want to contribute on this, can I? and also I would like to change the `navbar a` color to white so links will be visible on the background color, else pink color that background makes hard to find the nav links.

Yes you can

**Comment by Akshat2Jain** [comment]
This issue has been resolved
