### ISSUE TITLE
change the color and font size of the blog heading

### ISSUE THREAD

**Issue by Akshat2Jain** [Akshat2Jain/blogapp_reactjs#4]
Change the colour of the blog heading to black and add property font-size of 1.5rem.

## This is how it looks
![Screenshot from 2022-07-06 16-32-25](https://user-images.githubusercontent.com/101265586/177760230-13802c15-91f4-4225-ae06-f5d8e084673e.png)

## To contribute
- src->index.css
- In .blog-details h2 change color to black and add property font-size:1.5rem

**Comment by Akshat2Jain** [comment]
This is beginner friendly issue . Plz contribute

**Comment by Harshvardhantomar** [comment]
I would like to try to solve this issue. Can u assign it to me and also tell me how to start with the issue?

**Comment by cod-lvr** [comment]
hello, i worked on this easy fixing and forked the project for any help in future.

**Comment by Akshat2Jain** [comment]
Thank You everyone for their contribution!!
Plz do follow me on github
