### ISSUE TITLE
Add 404 page not found

### ISSUE THREAD

**Issue by Akshat2Jain** [Akshat2Jain/blogapp_reactjs#6]
Add a 404 page not found if we enter the wrong URL

### Follow these steps
- src->components-> make a new component name NotFound.js
- add this code

```
 const NotFound = () => {
  return (
    <div className="not-found">
         <h2>Sorry</h2>
      <p>That page cannot be found</p>
    </div>
  );
}
```
 
export default NotFound;
- then export it 
- then go to app.js ,import it and a new route and write this code
- `<Route path="*">
              <NotFound />
            </Route>`
   

### Best of luck

**Comment by FloatingDorito** [comment]
Hello, I would like to contribute on fixing the issue

**Comment by Akshat2Jain** [comment]
> Hello, I would like to contribute on fixing the issue

Yes, you can!

**Comment by FloatingDorito** [comment]
Hi! I am done fixing the issue
at `<Route path="*"> <NotFound /> </Route>`
I changed to `<Route path="/error404"> <NotFound /> </Route>`
![image](https://user-images.githubusercontent.com/52376777/177896057-f657bb8c-27cd-4e19-8428-69f33ea03982.png)

**Comment by Akshat2Jain** [comment]
Create a pull request plz so that I can see the changes

**Comment by FloatingDorito** [comment]
> Create a pull request plz so that I can see the changes

Created
